
import './App.css';
import Data from './Data';
import Card from './Card';


   function App(){
       return(
        
        <>

    <Card
        imgsrc={Data[0].imgsrc}
        title={Data[0].title}
        sname={Data[0].sname}
        link={Data[0].link}
        city={Data[0].city}
        country={Data[0].country}
        contact={Data[0].contact}
        education={Data[0].education}
        zipcode={Data[0].zipcode}
        idno={Data[0].idno}
        laptop={Data[0].laptop}
      /> 
    <Card
        imgsrc={Data[1].imgsrc}
        title={Data[1].title}
        sname={Data[1].sname}
        link={Data[1].link}
        city={Data[1].city}
        country={Data[1].country}
        contact={Data[1].contact}
        education={Data[1].education}
        zipcode={Data[1].zipcode}
        idno={Data[1].idno}
        laptop={Data[1].laptop}
      />
      <Card
        imgsrc={Data[2].imgsrc}
        title={Data[2].title}
        sname={Data[2].sname}
        link={Data[2].link}
        city={Data[2].city}
        country={Data[2].country}
        contact={Data[2].contact}
        education={Data[2].education}
        zipcode={Data[2].zipcode}
        idno={Data[2].idno}
        laptop={Data[2].laptop}
      />
      <Card
        imgsrc={Data[3].imgsrc}
        title={Data[3].title}
        sname={Data[3].sname}
        link={Data[3].link}
        city={Data[3].city}
        country={Data[3].country}
        contact={Data[3].contact}
        education={Data[3].education}
        zipcode={Data[3].zipcode}
        idno={Data[3].idno}
        laptop={Data[3].laptop}
      />
      <Card
        imgsrc={Data[4].imgsrc}
        title={Data[4].title}
        sname={Data[4].sname}
        link={Data[4].link}
        city={Data[4].city}
        country={Data[4].country}
        contact={Data[4].contact}
        education={Data[4].education}
        zipcode={Data[4].zipcode}
        idno={Data[4].idno}
        laptop={Data[4].laptop}
      />
      <Card
        imgsrc={Data[5].imgsrc}
        title={Data[5].title}
        sname={Data[5].sname}
        link={Data[5].link}
        city={Data[5].city}
        country={Data[5].country}
        contact={Data[5].contact}
        education={Data[5].education}
        zipcode={Data[5].zipcode}
        idno={Data[5].idno}
        laptop={Data[5].laptop}
      />
      <Card
        imgsrc={Data[6].imgsrc}
        title={Data[6].title}
        sname={Data[6].sname}
        link={Data[6].link}
        city={Data[6].city}
        country={Data[6].country}
        contact={Data[6].contact}
        education={Data[6].education}
        zipcode={Data[6].zipcode}
        idno={Data[6].idno}
        laptop={Data[6].laptop}
      />
      <Card
        imgsrc={Data[7].imgsrc}
        title={Data[7].title}
        sname={Data[7].sname}
        link={Data[7].link}
        city={Data[7].city}
        country={Data[7].country}
        contact={Data[7].contact}
        education={Data[7].education}
        zipcode={Data[7].zipcode}
        idno={Data[7].idno}
        laptop={Data[7].laptop}
      />
      <Card
        imgsrc={Data[8].imgsrc}
        title={Data[8].title}
        sname={Data[8].sname}
        link={Data[8].link}
        city={Data[8].city}
        country={Data[8].country}
        contact={Data[8].contact}
        education={Data[8].education}
        zipcode={Data[8].zipcode}
        idno={Data[8].idno}
        laptop={Data[8].laptop}
      />
      <Card
        imgsrc={Data[9].imgsrc}
        title={Data[9].title}
        sname={Data[9].sname}
        link={Data[9].link}
        city={Data[9].city}
        country={Data[9].country}
        contact={Data[9].contact}
        education={Data[9].education}
        zipcode={Data[9].zipcode}
        idno={Data[9].idno}
        laptop={Data[9].laptop}
      />

           </>
       );
   }
     export default App;